default-editor: code
pkg-installers: # these are run in order
  # Ubuntu
  - name: apt
    os: linux
    lsb-id: ubuntu
    pre: sudo apt-get update
    install-cmd: sudo apt-get install {{.PkgName}} -yqq
    pkgs:
      - tmux
      - cmake
      - apt-transport-https
      - wget
      - ca-certificates
      - software-properties-common
      - snapd
      - git
      - xclip
      - net-tools

  # All linux distros
  - name: snap
    os: linux
    cmd: "sudo snap install {{.PkgName}}"
    pkgs:
      - jq
      - yq

  # Mac OS
  - name: brew
    os: darwin
    pre: "[ -x \"$(command -v brew)\" ] || /usr/bin/ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
    install-cmd: brew install {{.PkgName}}
    pkgs:


brew: # stuff from [homebrew](https://brew.sh/) - for mac
choco: # stuff from [chocolatey](https://chocolatey.org/) - for windows
link:
  - os: unix
    src:  "{{.ZetupDir}}/dotfiles/bashrc.sh"
    target: "{{.Home}}/.bashrc"
  - os: unix
    src:  "{{.ZetupDir}}/dotfiles/aliases.sh"
    target: "{{.Home}}/.aliases"
  - os: unix
    src:  "{{.ZetupDir}}/dotfiles/fns.sh"
    target: "{{.Home}}/.fns"
  - os: unix
    src: "{{.ZetupDir}}/dotfiles/vimrc"
    target: "{{.Home}}/.vimrc"
  - os: unix
    src: "{{.ZetupDir}}/dotfiles/tmux.conf"
    target: "{{.Home}}/.tmux.conf"
  - os: unix
    src: "{{.ZetupDir}}/startup/zetup.desktop"
    target: "{{.Home}}/.config/autostart/zetup.desktop"

projects: # put your github projects here, and they'll automatically be cloned to $HOME/dev
  - github.com/zetup-sh/zetup-pkg
