default-editor: code
snap: # packages to install with snap (linux)
  - jq
  - yq
brew: # brew will automatically be installed
  - wget
choco: # stuff from [chocolatey](https://chocolatey.org/) - for windows
  yarn
  nodejs.install
  gnuwin32-coreutils.install
  golang
  dep
  googlechrome
  git.install
  electron
  postgresql
  jq
  7zip.install
  autohotkey