type: editor
snap: # back to reality
  - code
link:
  - os: linux
    src:  "{{.ZetupDir}}/subpkg/vscode/config/keybindings.json"
    target: "{{.Home}}/.config/Code/User/keybindings.json"
  - os: linux
    src:  "{{.ZetupDir}}/subpkg/vscode/config/settings.json"
    target: "{{.Home}}/.config/Code/User/settings.json"
